### PR TITLE
fix(Series): check null pointer

### PR DESCRIPTION
**Pull request by howel52**
close: https://github.com/hustcc/echarts-for-react/issues/276

### CODE REVIEW

**Comment by pissang** [comment]
@howel52 Thanks for the contribution. Can you provide a test case?

**Comment by howel52** [comment]
@pissang I did not reproduce this error,  but I found some similar errors.

1. https://github.com/apache/incubator-echarts/issues/8870
2. https://github.com/hustcc/echarts-for-react/issues/276

**Comment by howel52** [comment]
hi,  @100pah How is the progress of this PR.  

And, these changes in this PR will have no side effects.

**Comment by pissang** [comment]
@howel52 @100pah Merged. But I'm afraid it's a temporary defensive solution. Perhaps there is something else more serious underlying. We should look into it.

**Pull request merged**
