### PR TITLE
Update BMapCoordSys default dimensions

### PR DESCRIPTION
**Pull request by LianJilu**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing

### Fixed issues

#11528

### Before: What was the problem?

bmap tooltip display the latitude not the value

### After: How is it fixed in this PR?

change the BMapCoordSys.prototype.dimensions = ['lng', 'lat'] to 
BMapCoordSys.prototype.dimensions = ['lng', 'lat', 'value'];

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by yufeng04** [comment]
I find that this problem seems to be more complicated than expected. The problem may be dealing with the data dimension of the scatter chart

**Comment by LianJilu** [comment]
can you show some the wrong data dimension of scatter chart not from bmap @yufeng04

**Comment by kristalhu** [comment]
Hey Do u know how can I find out I’m hacked in phone?


Sent from Yahoo Mail for iPhone


On utorok, decembra 31, 2019, 3:36 AM, jimmylian <notifications@github.com> wrote:


can you show some the wrong data dimension of scatter chart not from bmap @yufeng04

**Comment by yufeng04** [comment]
@LianJilu There are some data that I printed out on the console. The `tooltipDims` should be `["value"]`. The code is [here](https://github.com/apache/incubator-echarts/blob/master/src/model/Series.js#L398).
image

**Comment by LianJilu** [comment]
> @LianJilu There are some data that I printed out on the console. The `tooltipDims` should be `["value"]`. The code is [here](https://github.com/apache/incubator-echarts/blob/master/src/model/Series.js#L398).
> image

I find the the tooltipDim of line and bar is also 'y', and the geo is 'lat', pie is 'value', it is seems to be the dimension problem. The Coordinate System Instance has the dimensions and getDimensionsInfo Interface, maybe we should find in it.

**Comment by LianJilu** [comment]
If I modify the dimensions of BMapCoordSys, the tooltipDim change to 'value'.
image

**Comment by pissang** [comment]
Hi @LianJilu The dimension in `bmap` has no problem. It means dimension this coordinate system can provide. Not dimensions data provided.

**Pull request closed without merging**
