### PR TITLE
[12979] fix bug of overriding magictype buttons' title when click the…

### PR DESCRIPTION
**Pull request by pingf**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

fix bug of overriding the button title of the tool box

currently, if we change the title of the magic-type button in the toolbox, it works as expected
however, if we click the button for stack view, all magic type buttons' titles revert to the default 
our users just want a chart without chinese, I guess this is the final block!
 

### Fixed issues

- #12979 
 

### Before: What was the problem?

to check this one, we need do sth like this
```js
toolbox: {
               ......
                magicType: {
                    show: true,
                    type: ['line', 'bar', 'stack'],
                    title: {
                        line: 'line view',
                        bar: 'bar view',
                        stack: 'stack view',
                        tiled: 'tiled view',
                    },
                },
             ......
}      
```

as stack and tiled are sth like a pair, we need to set the title for the tiled

but it only works if we never click the stack button,
once we click the button for stack, all titles revert to the the default chinese ones

image

### After: How is it fixed in this PR?

the old code use magicTypeLang.title as the base to override the new title
however, this is the one of fixed chinese

and now I change the logic to flip the title of stack and tiled when we click, and use model.option to get the title dynamically

```js
newTitle = zrUtil.merge(
            {
                      stack: model.option.title.tiled,
                      tiled: model.option.title.stack
            }, model.option.title);
```

and now it works as expected

image

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by susiwen8** [comment]
@pingf Thank you very much, could you submit this PR to `next` branch? Also please provide a related test case.

**Comment by pingf** [comment]
@susiwen8 
sorry for the wrong branch, this is the first time I created PR here, 
and just followed the https://github.com/apache/incubator-echarts/wiki/How-to-make-a-pull-request#coding-standard 
it seems it didn't mention the next branch.

I'll create another PR to next then

**Comment by pingf** [comment]
@susiwen8 
I've change the merge base from master to next, it seems it has a lot of conflicts
I guess all of these can be ignored  as this PR only changes a small part of one file.

so if I want to create PR next time , which branch should I use as the base branch ?  the master or next?

**Comment by susiwen8** [comment]
@pingf since too much conflict,, It's better to create a new PR for `next` and close this one. Base brach you chose should be `next`.

**Comment by pingf** [comment]
arrr...  the changes in next are huge, even migrated to typescripts.....
I think it really needs a new wiki page for this, even the next is not released

**Comment by susiwen8** [comment]
Check out https://github.com/apache/incubator-echarts/issues/12926

**Comment by pingf** [comment]
@susiwen8 
thx, I've test the next branch, it seems the issue 12979 is already been fixed
but during test the code, find another problem, after some clicks of the buttons in the toolbox, the chart freezes!
I'll create a issue to describe it in detail

**Pull request closed without merging**
