### PR TITLE
refinement: shortened _trim regex

### PR DESCRIPTION
**Pull request by Andrew-He**
make it shorter and sweet. tiny pr : )

### CODE REVIEW

**Comment by Ovilia** [comment]
Thanks @Andrew-He for your contribution!
Do you mind providing some test cases using simple `assert` on https://jsfiddle.net .
Because `trim` is some old logic, we have to make sure the change works.

**Comment by Andrew-He** [comment]
Hi, Ovilia, 
      here is the link to test cases I 've written, please verify it. thanks.
           https://codepen.io/andrew-he/pen/LKELBV
      thanks

**Comment by Andrew-He** [comment]
> Hi, Ovilia,
> here is the link to test cases I 've written, please verify it. thanks.
> https://codepen.io/andrew-he/pen/LKELBV
> thanks

@Ovilia

**Comment by Andrew-He** [comment]
I know you guys are busy, but I have to say it is pretty slow-paced.

**Pull request merged**
