### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by YvesR**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

Added German translation for the project.

### CODE REVIEW

**Review by nelsonbbarriento23 — APPROVED** [review]

**Comment by YvesR** [comment]
Hello, as this PR is approved, why it is still blocked for merge? Anything I missed?

**Comment by susiwen8** [comment]
Because it's not approved by someone who has write access for this project, also, could you change base branch to `next`？

**Comment by YvesR** [comment]
> Because it's not approved by someone who has write access for this project, also, could you change base branch to `next`？

Lots of conflicts on these branch. Should I better close this PR and rebase to `next` before?

**Comment by susiwen8** [comment]
Yes, you can close this one and make a new PR for `next`

**Pull request closed without merging**
