### PR TITLE
Fix #12642, add line height for axispointer

### LINKED ISSUE #12642: tooltip.axisPointer.label 设置 lineHeight 无效果
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xkb87pE09r&v=1](https://gallery.echartsjs.com/editor.html?c=xkb87pE09r&v=1)

### Steps to reproduce
tooltip.axisPointer.label 设置 lineHeight 

### What is expected?
设置 lineHeight 生效

### What is actually happening?
tooltip.axisPointer.label 设置 lineHeight 无效

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Pass `line height` to `getBoundingRect`

### Fixed issues

Close #12642 

### Before: What was the problem?

Screen Shot 2020-05-20 at 17 56 49

### After: How is it fixed in this PR?

Screen Shot 2020-05-20 at 17 56 21

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by wf123537200** [comment]
I try to fix the issue like this too, but i  thought the result seem set the ```height``` but no ```lineHeight```,and i didn't find a good way to solve it.😁

Maybe the label should be centered vertically?

**Comment by plainheart** [comment]
In fact, I did a test about this a few days ago and the result is that besides `lineHeight`, there are more properties are invalid for `tooltip.axisPointer.label` such as `width`, `height`,  `textShadowColor`, `textBorderColor`, `textBorderWidth`.
Maybe this PR can fix them in a row.

**Comment by susiwen8** [comment]
> I try to fix the issue like this too, but i thought the result seem set the `height` but no `lineHeight`,and i didn't find a good way to solve it.😁
> 
> Maybe the label should be centered vertically?

@wf123537200  Woo, You were right, Didn't notice it,  :sweat_smile:

**Comment by susiwen8** [comment]
> In fact, I did a test about this a few days ago and the result is that besides `lineHeight`, there are more properties are invalid for `tooltip.axisPointer.label` such as `width`, `height`, `textShadowColor`, `textBorderColor`, `textBorderWidth`.
> Maybe this PR can continue to finish the [`TODO: rich` at line 90](https://github.com/apache/incubator-echarts/blob/master/src/component/axisPointer/viewHelper.js#L90) to fix them in a row.

Thanks for heads up, I will try

**Comment by plainheart** [comment]
Hi~ @susiwen8 Thanks your fixing.
I've been inspired by following code lines from @Ovilia ~
Maybe we can make some changes like this
https://github.com/apache/incubator-echarts/blob/5a94212c43f0a4b5a8da7c26cf20192d29fb1d02/src/component/tooltip/TooltipRichContent.js#L139-L147

As mentioned above, there may be no need to solve this issue as present scheme.
```js
var textRect = textContain.getBoundingRect(text, font, null, null, null, labelModel.get('lineHeight'));
```

Some changes are as follows
```js
style: graphic.setTextStyle({}, labelModel, {
    text: text,
    fill: bgColor,
    stroke: labelModel.get('borderColor') || 'transparent',
    lineWidth: labelModel.get('borderWidth') || 0,
    textFont: font,
    textPosition: 'inside',
    textPadding: paddings,
    textFill: labelModel.getTextColor()
})
```
This can solve the issue that `lineHeight` is invalid and in the meanwhile, there are more supported properties of label.(Note that some new supported properties are now missing description in the official document)
```js
label: {
    fontWeight: 'bold',
    fontSize: 20,
    textShadowBlur: 10,
    textShadowOffsetX: 10,
    textShadowOffsetY: 10,
    textShadowColor: 'red',
    backgroundColor: 'yellow',
    textBorderColor: 'blue',
    textBorderWidth: 5,
    borderWidth: 2,
    borderColor: 'cyan',
    padding: [10, 20, 30, 40],
    shadowColor: 'green',
    shadowBlur: 5,
    shadowOffsetX: 10,
    shadowOffsetY: 10,
    borderRadius: 20,
    lineHeight: 40,
    color: 'purple',
    // width: 400, // rich is needed, but rich is TODO
    // height: 200, // rich is needed, but rich is TODO
}
```
A test screenshot(Just for test, No beauty)

image

Looks good.

In the last, that's a pity rich label is still a TODO. I have no idea about it by now, but I think we can refer to implements of [TooltipRichContent](https://github.com/apache/incubator-echarts/blob/5a94212c43f0a4b5a8da7c26cf20192d29fb1d02/src/component/tooltip/TooltipRichContent.js#L74-L108) 

Let we make it right together~ : )

**Comment by susiwen8** [comment]
@plainheart Would you submit a new PR for it?

**Comment by plainheart** [comment]
Sorry, that's only my suggestions and I thought you would finish it. Now you have closed this issue, I have to open a new one for this later. Feel free to give some advice on rich label. Thank you!

**Comment by susiwen8** [comment]
> Sorry, that's only my suggestion and I thought you would finish it. Now you have closed this issue, I have to open a new one for this later. Feel free to give some advice on rich label. Thank you!

:smiley :smiley :smiley I agree with you. You solution is the right way to fix this issue, no hard feeling. And to be honesty, I have ton of work to do, so I might not have time for it :joy: :joy: :joy:

**Pull request closed without merging**
