### PR TITLE
Add node align for the Sankey diagram

### PR DESCRIPTION
**Pull request by jas0ncn**
Currently, the Sankey diagram will align all the node without `outEgdes` in the last column.
It doesn't make sense when I draw a flow diagram using Sankey.
I added the `align` option to `SankeySeries` and sets a default value `justify` which for compatible previous behaviors.
The other value for the `align` option is `left`, which will not trigger `moveSinksRight` function and keep node left.
Here are two pics for comparing them.
image

### CODE REVIEW

**Comment by Ovilia** [comment]
Please remove the files under dist.

**Comment by jas0ncn** [comment]
Ok, I removed them, thanks!

**Comment by Ovilia** [comment]
You should not remove the files under dist. Instead, you should keep them unchanged.

**Comment by Ovilia** [comment]
Thanks for your contribution! @deqingli will have a closer look at it.

**Comment by Ovilia** [comment]
Hi @jas0ncn . Can you provide a further explanation of how this `align` works? For example, if it is set to be `'left'`, and parent level is `n`, will its child be place at `n + 1` position? Or can it set to be at `leafN - x` position, where `leafN` is the level of leaves and `x` can be configured?

**Comment by jas0ncn** [comment]
@deqingli Thanks reply! I agree with you, is there a timetable for implementing `layout`?

**Comment by deqingli** [comment]
@jas0ncn  If nothing unexpected happens, I am going to release it in the next version.

Best Wishes,
Deqing

**Comment by jas0ncn** [comment]
Thanks! waiting for it 👍

**Pull request closed without merging**
