### PR TITLE
fix(axisLabel): fix axisLabel rotating with grid.containLabel #12259

### LINKED ISSUE #12259: 在grid.containLabel模式下xAxis的rotate算错了
### Version
4.7.0-rc.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xOcNMBdkE&v=1](https://gallery.echartsjs.com/editor.html?c=xOcNMBdkE&v=1)

### Steps to reproduce
左图空白多了一截，右图减了不该减的一截。应该是算sin取值的时候正负取得不对

### What is expected?
旋转后x轴label刚好与图表边缘相切

### What is actually happening?
不正确的取值

### PR DESCRIPTION
**Pull request by quillblue**
## Brief Information

This pull request is in the type of:

- [X] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?
Update function of calculating updated height & width for rotated axis labels
Fix issue #12259

### Fixed issues

Close #12259

## Details
In previous `rotateTextRect()` in axisHelper.js, take cos value of negative rotate will got negative result, which causes calculated width/height of rotated axis label is smaller than actual size. In grid, it will cause axis labels be cut.

### After: How is it fixed in this PR?
As physically we need cos/sin of rotate angle to be positive (or 0), add Math.abs here to solve this issue,

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [X] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by quillblue** [comment]
@susiwen8 Thanks for kind reminder. Revert changes in `dist ` back to previous version in new commit. Accordingly please squash to one during merging.

**Comment by susiwen8** [comment]
@quillblue Could you add a test case for this PR?

**Comment by quillblue** [comment]
@susiwen8 Sure. In latest commit I added a test case using same option as original issue [using](https://gallery.echartsjs.com/editor.html?c=xOcNMBdkE&v=1)
and below are before&after comparision
Before:
Before

After:
After

**Comment by quillblue** [comment]
@Ovilia combined to `axisLabel.html` case 2 per your idea. The existing case has animation to show the rotate of labels, which has greater idea than my demo.
Though `rotate: 330` is same as `rotate: -30`, I set xAxis rotate from -180 to 180 (instead of 0-360) as users are more used to use negative value to represent clockwise rotation.

**Pull request merged**
