### PR TITLE
feat(datastack):stack support positive add negative, close 12699

### PR DESCRIPTION
**Pull request by wf123537200**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?
stack support positive add negative

### Fixed issues

#12699 

### Before: What was the problem?

image

### After: How is it fixed in this PR?

image

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

toolbox-stack.html

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by pissang** [comment]
Thanks for the contribution @wf123537200 !

Separated stacking on positive and negative values is by design.
If necessary, we can make it configurable to support stacking positive values on negative values.

**Comment by wf123537200** [comment]
> Thanks for the contribution @wf123537200 !
> 
> Separated stacking on positive and negative values is by design.
> If necessary, we can make it configurable to support stacking positive values on negative values.

Thank you for review and i will add the config to handle the situation later
Is it reasonable to add it to the ```toolbox.feature.magicType```?
Is there any suggestion where to add configuration items.

**Comment by pissang** [comment]
@wf123537200 I think it can be an option related to `stack`. Like `stackDifferentSign`(I just think of it. Perhaps there is a better name.

**Comment by wf123537200** [comment]
i try to support this situation, but i find when the type='line' is ok, but when switch the type='bar' the result become strange.
so close the pr, not support

**Pull request closed without merging**
