### PR TITLE
Fix #13130: make labelLine z option configurable

### LINKED ISSUE #13130: 5.0的Alpha版本地图上的labelLine被地图色块遮挡
### Version
5.0.0-alpha.1

### Steps to reproduce
地图加上labelLine即可

### What is expected?
地图上的labelLine被地图色块不被遮挡

### What is actually happening?
地图上的labelLine被地图色块遮挡

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

Make `labelLine` `z` configurable

### Fixed issues

Close #13130 

### Before: What was the problem?
`labelLine` might be under some `section`
image

### After: How is it fixed in this PR?
Add an option for `labelLine` `z`, so user can control `labelLine`'s z level
Screen Shot 2020-08-17 at 21 22 31

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by susiwen8** [comment]
But I'm not sure `updateLabelLinePoints` is the right place to set `z`. Also, should we add default value?

**Comment by pissang** [comment]
I think we should make the configuration simpler to be understood.

For example, only a boolean value to indicate if the labelLine is on top of the polygon.

Because `z` value usually is not a consistent value.  Developers need to guess which z should be used so the labelLine can be on top of the polygon.

**Comment by susiwen8** [comment]
@pissang How can we assure `labelLine` is absolutely at top of canvas? Cause we provide `z` and `zlevel` to user

**Comment by susiwen8** [comment]
> @pissang How can we assure `labelLine` is absolutely at top of canvas? Cause we provide `z` and `zlevel` to user

I have tried `Infinity`, seem works. In order to make it more flexible, could we add two more options? `z: number` and `alwaysOntop: boolean`? @pissang

**Comment by pissang** [comment]
What we want is to put the labelLine on top of the polygon on the map. So we only need to make sure it has larger `z` than the polygon.

Also, we should always take it carefully when exposing more low-level concepts to options.  If we expose z and zLevel on the `labelLine`. It means we also need to make it configurable in `label` or other elements. It will make it complex and hard for us to make changes in the further.

**Comment by pissang** [comment]
@susiwen8 `z` should always be the same since it's configured by developers

**Pull request closed without merging**
