### PR TITLE
fix(line): fix `symbolRotate` for `markLine` does not work. close #12388.

### LINKED ISSUE #12388: Symbol rotate for markLine dose not work on line chart
### Version
4.7.0

### Reproduction link
[https://www.echartsjs.com/examples/zh/editor.html?c=line-aqi](https://www.echartsjs.com/examples/zh/editor.html?c=line-aqi)

### Steps to reproduce
I just add the following code in `markLine` and it doesn't work,
```
symbol: 'triangle',
symbolRotate: 90,
```
Since this option is listed in the document, I suppose it should work.

### What is expected?
The symbol will rotate.

### What is actually happening?
The symbol dose not rotate.

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Fix the option `symbolRotate` in `markLine` does not work for line series. Close #12388.

### Fixed issues

- #12388

### Related test cases

Refer to `test/markLine-symbolRotate.html`

### CODE REVIEW

**Comment by YiYingWu1302** [comment]
It works perfect for me! Thanks for quick fixing :)

**Comment by YiYingWu1302** [comment]
Another question,
Before when setting `symbol` in `makrLine`, two symbols with different directions will be created as shown below
螢幕快照 2020-04-08 上午10 37 16
now the symbols will point to the same direction as shown below
螢幕快照 2020-04-08 上午10 38 38
Just wonder is this expected?

**Comment by plainheart** [comment]
@YiYingWu1302 Could you provide an example?

**Comment by YiYingWu1302** [comment]
@plainheart I set `symbol` in `makrLine` instead of `markLine.data`
```js
markLine: {
  symbol: 'triangle'
}
```

**Comment by plainheart** [comment]
THX! That's not expected. I've made a fix for it, now it should work well. A default rotation action would be performed if `symbolRotate` is not specified(undefined or null) or `NaN`.  You can refer to this commit https://github.com/apache/incubator-echarts/pull/12392/commits/f949aebae88fd518711a67ca2b6812ec44689494 for more details.

**Comment by YiYingWu1302** [comment]
It works well!
Just come up with an idea, since `symbol` supports `Array` as value, to set `fromSymbol`and `toSymbol`, is it possible `Array` is also supported for `symbolRotate` to set `fromSymbol` & `toSymbol`'s rotation?
Like below
```js
markLine: {
  symbol: 'triangle',
  symbolRotate: [0, 180]
}
```

**Comment by plainheart** [comment]
@YiYingWu1302 That's OK, but we may have to wait until this PR is merged since current PR is for fixing. After it is merged,  you can open a feature request issue for these requirements. BTW, sorry for late reply. :）

**Comment by YiYingWu1302** [comment]
@plainheart I get it. Thanks for your kindly reply!

**Comment by plainheart** [comment]
> It works well!
> Just come up with an idea, since `symbol` supports `Array` as value, to set `fromSymbol`and `toSymbol`, is it possible `Array` is also supported for `symbolRotate` to set `fromSymbol` & `toSymbol`'s rotation?
> Like below
> 
> ```js
> markLine: {
>   symbol: 'triangle',
>   symbolRotate: [0, 180]
> }
> ```

Hi~ @YiYingWu1302 I've made some commits for this feature you mentioned about two months ago.   
Please feel free to see #12736 for details.

**Pull request merged**
