### PR TITLE
add: Japanese i18n file

### PR DESCRIPTION
**Pull request by swsoyee**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

Support Japanese.

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### Other information

The terms were chosen with reference to the original Chinese and English translations file, and all Japanese terms have been subjected to detailed academic research, so there should be no problem.
参考了中文原文和英语翻译的基础上选择的术语，且所有日语术语皆经过了详细的学术调研，应该没什么问题。

### CODE REVIEW

**Comment by plainheart** [comment]
Thank you for providing the Japanese translation.
We are working on the release of the next version 5.0. Would you mind moving this commit to the `next` branch? 

All the language source files are in https://github.com/apache/incubator-echarts/tree/next/src/i18n
https://github.com/apache/incubator-echarts/blob/next/src/i18n/langEN.ts is a template for your reference.

Thanks again.

**Comment by plainheart** [comment]
Hi, there is some work to be done
- [ ] Move the translation file to https://github.com/apache/incubator-echarts/tree/next/src/i18n/langJA.ts
- [ ] Add translations for [time](https://github.com/apache/incubator-echarts/blob/next/src/i18n/langEN.ts#L25-L40) section.

**Comment by swsoyee** [comment]
@plainheart Sorry for the delay, translation have been added, also switch the target branch and moved the file into `src/i18n` directory.

**Review by plainheart — APPROVED** [review]
It looks good to me. Please @pissang have a look. Then I think we can merge this pull request.

**Review by pissang — APPROVED** [review]

**Pull request merged**
