### PR TITLE
[line] add  visualColorAccessPath

### PR DESCRIPTION
**Pull request by Ende93**
So the `legend` can gets the color of `line`

### CODE REVIEW

**Comment by Ovilia** [comment]
Thanks for your contribution!

We do think legend needs some enhancement, not only for the line color. But it's OK to make a PR only about the line color.
But I think there may be some problems with this PR.

```js
option = {
    title: {
        text: 'Awesome Chart'
    },
    xAxis: {
        data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },
    yAxis: {},
    series: [{
        type: 'line',
        name: 'a',
        data:[220, 182, 191, 234, 290, 330, 310],
        lineStyle: {
            color: 'blue'
        },
        itemStyle: {
            color: 'green'
        }
    }],
    legend: {
        data: ['a']
    }
};
```

For a test case like this, the item color (border of small circles) is blue after change, but it's expected to be green, as the `itemStyle.color` defines.

@100pah Any comments?

**Comment by Ende93** [comment]
Never though about the `itemStyle.color`, I think that the color of legend shoud the same as line not the symbol style. But for back compat?I could try to set `lineStyle.color` when `itemStyle.color` is `undefined`.Is that ok?

**Comment by Ovilia** [comment]
We cannot assume item color is the same as line color.
For the time being, please wait for @100pah for the view.

**Comment by Ovilia** [comment]
This PR is closed due to stale dated.

**Pull request closed without merging**
