### PR TITLE
german translation added

### PR DESCRIPTION
**Pull request by YvesR**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

Added german translation

### CODE REVIEW

**Comment by YvesR** [comment]
@susiwen8 Added in new format. Please review.

> I didn't dig into the changed i18n settings, just translated, so if you have to register `DE` as language in a config file, please advice.

**Comment by pissang** [comment]
Hi, @YvesR Thanks for the contribution. The language source file is in the https://github.com/apache/incubator-echarts/tree/next/src/i18n

https://github.com/apache/incubator-echarts/blob/next/src/i18n/langEN.ts is an example template.

**Comment by YvesR** [comment]
> Hi, @YvesR Thanks for the contribution.
> 
> The language source files are in the https://github.com/apache/incubator-echarts/tree/next/src/i18n
> 
> https://github.com/apache/incubator-echarts/blob/next/src/i18n/langEN.ts is an example template.

Thanks for info, translation the wrong file. Ok, did add a new german ts file and commited.

**Review by pissang — APPROVED** [review]

**Comment by pissang** [comment]
Looks good, thanks!

**Pull request merged**
