### PR TITLE
Tooltip dom append to body, use to top of layer

### PR DESCRIPTION
**Pull request by xinpureZhu**
#4627 解决 Tooltip 被其它图形遮挡的问题

### CODE REVIEW

**Comment by pissang** [comment]
谢谢！这个 PR 中没有处理 tooltip 组件移除或者图表 dispose 后浮层的移除

**Comment by xinpureZhu** [comment]
疏乎了，已补上提交

**Comment by balthazar** [comment]
你好! Any update on this?

**Comment by JoenZhu** [comment]
can anyone merge this pr?

**Comment by JoenZhu** [comment]
can anyone merge this pr?

**Comment by 100pah** [comment]
This issue will be merged. Thanks the contribution of @xinpureZhu .

But a new option `tooltip.appendToBody` will be added to open this feature.
By default `tooltip.appendToBody` should be `false`, otherwise it is probably a big break change for some existing deep-customization usage. 
And there would be more factors needed to be considered to ensure the "append to body" works correctly. Subsequent PR is under way.

**Pull request merged**
