### PR TITLE
Fix negetive number or string exist in dimensions array, the correspo…

### LINKED ISSUE #10343: 在多折线图里，如果dimensions里有负数，则其对应的那条折线无法绘制
### Version
4.1.0-rc.1

### Reproduction link
[https://codepen.io/SonnyW/pen/axaOvy](https://codepen.io/SonnyW/pen/axaOvy)

### Steps to reproduce
见链接

### What is expected?
负数对应的曲线可绘制

### What is actually happening?
没有绘制

### PR DESCRIPTION
**Pull request by susiwen8**
…nding line won't show (#10343)

Close #10343

### CODE REVIEW

**Comment by susiwen8** [comment]
@100pah Could you review this PR?

**Comment by susiwen8** [comment]
@Ovilia Thanks for your enlightenment, I didn't understand why you need check negative number at the time. I have corrected my code, please check it.

**Comment by 100pah** [comment]
> @Ovilia Thanks for your enlightenment, I didn't understand why you need check negative number at the time. I have corrected my code, please check it.

It is a feature that use negative dimension value to prevent that dimension be filtered or processed in the workflow.

**Comment by Ovilia** [comment]
@susiwen8 Thanks for your contribution. That really helps a lot!

**Pull request merged**
