### PR TITLE
Add husky

### PR DESCRIPTION
**Pull request by wf123537200**
## Brief Information
because i pull request without run  ```npm run lint```, and the ide is not warned me, so i add husky to make sure the eslint has been check before commit.

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

add husky and pre-commit task to keep the code style consistent

### Before: What was the problem?

may commit a pr without check the code style

### After: How is it fixed in this PR?

the commit will interrupt by the git-hook (husky)

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by susiwen8** [comment]
Thanks, That's very useful.

**Comment by pissang** [comment]
Thanks! It seems this PR also includes the content in your earlier PR https://github.com/apache/incubator-echarts/pull/12487. Can you separate it so we can merge this PR ASAP

**Comment by wf123537200** [comment]
Hi~~The husky is already separated, i think the  last commit at PR #12487 not includes the husky, i use ```npm run lint``` to keep the code style. So this PR can be merge alone

**Comment by pissang** [comment]
Hi, the changed files in this PR shows the change in https://github.com/apache/incubator-echarts/pull/12487 is also included. I think husky in this PR can be merged alone when we are still discussing https://github.com/apache/incubator-echarts/pull/12487.

**Pull request closed without merging**
